---
#
# Execute all RPC support playbooks
#
- import_playbook: configure-packagemanager.yml
- import_playbook: configure-bash-environment.yml
- import_playbook: configure-hosts.yml
- import_playbook: configure-neutron.yml
- import_playbook: configure-nova.yml
- import_playbook: configure-glance.yml
# Disabled due to incompatiblities with
# the upstream version
#- import_playbook: configure-spice-console.yml
- import_playbook: install-holland-db-backup.yml
- import_playbook: install-dell-server-monitoring.yml
- import_playbook: install-hp-server-monitoring.yml
- import_playbook: install-hw-raid-tools.yml
- import_playbook: install-pccommon.yml
- import_playbook: install-sos-tool.yml
- import_playbook: install-consul.yml
- import_playbook: support-key.yml
